feat(concept): concept controller와 class 추가, search method 추가
linewalks/be-common pull request #25
Opened 2021-08-17 09:10 UTC by Jaymel

drug_exposure, condition_occurrence 테이블을 추가하고
Search class에 search method를 추가했습니다.
Concept class와 Concept controller를 만들었습니다.

GET /api/concept/index:
    keyword search 시 사용되는 keyword에 대한 설명과
    page, page_cnt에 대한 설명을 얻을 수 있습니다.

GET /api/concept/search:  
    keyword 쿼리 파라미터로 keyword 검색이 가능하며 
    page, page_cnt 쿼리 파라미터로 pagination이 가능합니다.

2021-08-17 09:21 UTC, westhyena requested changes

2021-08-17 09:21 UTC, westhyena commented on main/controllers/cdm/concept.py
> +def concept_keyword_search(**kwargs):
p3. use_kwargs를 이용해 Request Parameter를 정의했으니 패러미터 이름을 명시해주면 좋을듯합니다.
```python
def concept_keyword_search(page, page_cnt, keyword)
```

default 값을 설정하는 것이 필요해서 였다면 두 가지 방법이 있습니다.
```python
class RequestSearch(Schema):
  page = fields.Int(missing=1)
  page_cnt = fields.int(missing=10)
  keyword = fields.Str(missing="gender")

def concept_keyword_search(page=1, page_cnt=10, keyword="gender")
```
우리는 전자의 방법을 주로 썼습니다.

2021-08-17 09:21 UTC, westhyena commented on main/controllers/cdm/concept.py
> +def concept_keyword_search(**kwargs):
`*args, **kwargs`를 남발하는 것은 가독성을 해칩니다. (함수내에서 어떤 변수가 사용될지 알 기가 어려움)
꼭 필요한 경우에만 사용하면 좋겠습니다

2021-08-17 09:21 UTC, westhyena commented on main/models/cdm_data.py
> +        func.count(primary_col).desc()
정렬 기준도 parameter로 받으면 어떨까요?
어떤 것들이 올 수 있을지 고민해보고 추가해보면 좋겠습니다.

2021-08-17 09:21 UTC, westhyena commented on main/schema/cdm_schema.py
> +  return create_nested_list_schema(root_name, ConceptSearchCount, schema_name)
p3. 비슷한 형태의 함수가 계속 반복되는 듯합니다.
반복되는 것을 줄일 수 없을까요?

root_name으로부터 schema_name을 만드는 코드가 모두 동일하네요

2021-08-17 09:29 UTC, westhyena commented on main/models/cdm_data.py
> +  def search(cls, keyword):
p1. concept_name이나 concept_id에 keyword가 포함된 경우 검색하는 API가 있으면 좋겠습니다.
현재 구현하신 것은 검색이라기보단 

테이블별 가장 많이 나온 concept순서대로 보기에 가깝네요

2021-08-18 01:39 UTC, Jaymel commented on main/controllers/cdm/concept.py
> +def concept_keyword_search(**kwargs):
반영하겠습니다!

2021-08-18 09:12 UTC, Jaymel commented on main/models/cdm_data.py
> +        func.count(primary_col).desc()
order_key, desc 두 파라미터로 정렬의 기준이 될 컬럼 선택 및 오름차, 내림차순 정렬이 가능하게 바꿨습니다!

2021-08-18 09:12 UTC, Jaymel commented on main/schema/cdm_schema.py
> +  return create_nested_list_schema(root_name, ConceptSearchCount, schema_name)
코드를 묶어 반복을 줄였습니다!

2021-08-18 09:12 UTC, Jaymel commented on main/models/cdm_data.py
> +  def search(cls, keyword):
like를 사용한 키워드 검색으로 바꿨습니다!

2021-08-18 09:27 UTC, westhyena approved these changes

2021-08-18 09:30 UTC, yunsangr approved these changes

2021-08-18 09:37 UTC, merged